version: "3.3"
services:
  hazardtosociety:
    image: ghcr.io/ricardoalcaraz/hazardtosociety:latest
    container_name: HazardToSociety
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.hazardtosociety.rule=(Host(`hazardtosociety.com`) || Host(`www.hazardtosociety.com`))
      - traefik.http.routers.hazardtosociety.entrypoints=websecure
      - traefik.http.routers.hazardtosociety.tls=true
      - traefik.http.routers.hazardtosociety.tls.certresolver=le
    networks:
      - web
    environment:
      - NoaaApiToken=${NoaaApiToken}

networks:
  web:
    external: true