name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment:
      name: Prod
      
    runs-on: ubuntu-latest

    steps:
    - name: docker-ssh-redeploy
      uses: appleboy/ssh-action@master
      with:
        host: hazardtosociety.com
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/HazardToSociety/HazardToSociety
          ls -al
          docker-compose pull
          docker-compose up -d
